AWSTemplateFormatVersion: 2010-09-09
Description: Sample pipeline to use a S3-backed CF resource for mono-repo

Parameters:
  ThisPipelineYaml:
    Type: String
    Default: Source::mono-repo-s3-based/examples/cp-example-s3-pipeline.yaml

  BuildProjectName:
    Type: String
    Default: mono-repo-s3-example

  GitHubRepoName:
    Type: String
    Default: mono-repo-experiment
  GitHubBranchName:
    Type: String
    Default: master
  GitHubToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /github/my-token

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RestartExecutionOnUpdate: true
      Name: !Ref BuildProjectName
      RoleArn: RoleArnForYourCodePipeline
      ArtifactStore:
        Type: S3
        Location: BucketWhereArtifactsAreStored
        EncryptionKey:
          Id: ArtifactEncryptionKey
          Type: KMS
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: "1"
                Provider: GitHub
              RunOrder: 1
              Configuration:
                Owner: MyOrganization
                Repo: !Sub ${GitHubRepoName}
                PollForSourceChanges: false
                Branch: !Sub ${GitHubBranchName}
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: Source

        - Name: UpdateThisPipeline
          Actions:
            - Name: Update
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              RunOrder: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: !Ref AWS::StackName
                TemplatePath: !Ref ThisPipelineYaml
                RoleArn: RoleArnForYourCloudFormation
              InputArtifacts:
                - Name: Source

  PipelineTrigger:
    Type: Custom::MonoRepoTrigger
    Properties:
      ServiceToken: !ImportValue tools-MonoRepoTrigger # exported by the stack
      GitHubRepo: !Ref GitHubRepoName
      GitHubBranch: !Ref GitHubBranchName
      ChangeMatchExpressions: 'mono-repo-s3-based/.*'
      CodePipelineName: !Ref Pipeline
